# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-WSDL-Type
version:      0.02
version_from: lib/Pod/WSDL/Type.pm
installdirs:  site
requires:
    Pod::WSDL::Attr:               0.01
    Pod::WSDL::AUTOLOAD:           0.01
    Pod::WSDL::Utils:              0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
